//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.31 at 12:02:07 AM EDT 
//


package com.thomsonreuters.extractvalidator.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BuyerOrSellerLicenseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BuyerOrSellerLicenseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LICENSE_TYPE" type="{http://www.sabrix.com/services/taxcalculationservice/2011-09-01}LicenseType" minOccurs="0"/>
 *         &lt;element name="LICENSE_NUMBER" type="{http://www.sabrix.com/services/taxcalculationservice/2011-09-01}LicenseNumberType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BuyerOrSellerLicenseType", propOrder = {
    "licensetype",
    "licensenumber"
})
public class BuyerOrSellerLicenseType {

    @XmlElement(name = "LICENSE_TYPE")
    protected String licensetype;
    @XmlElement(name = "LICENSE_NUMBER")
    protected String licensenumber;

    /**
     * Gets the value of the licensetype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLICENSETYPE() {
        return licensetype;
    }

    /**
     * Sets the value of the licensetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLICENSETYPE(String value) {
        this.licensetype = value;
    }

    /**
     * Gets the value of the licensenumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLICENSENUMBER() {
        return licensenumber;
    }

    /**
     * Sets the value of the licensenumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLICENSENUMBER(String value) {
        this.licensenumber = value;
    }

}
