//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.31 at 12:02:07 AM EDT 
//


package com.thomsonreuters.extractvalidator.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CodeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CodeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CLASSIFICATION_CODE_TYPE" type="{http://www.sabrix.com/services/taxcalculationservice/2011-09-01}CodeTypeVal" minOccurs="0"/>
 *         &lt;element name="CLASSIFICATION_CODE_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CodeType", propOrder = {
    "classificationcodetype",
    "classificationcodeid"
})
public class CodeType {

    @XmlElement(name = "CLASSIFICATION_CODE_TYPE")
    protected CodeTypeVal classificationcodetype;
    @XmlElement(name = "CLASSIFICATION_CODE_ID")
    protected String classificationcodeid;

    /**
     * Gets the value of the classificationcodetype property.
     * 
     * @return
     *     possible object is
     *     {@link CodeTypeVal }
     *     
     */
    public CodeTypeVal getCLASSIFICATIONCODETYPE() {
        return classificationcodetype;
    }

    /**
     * Sets the value of the classificationcodetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeTypeVal }
     *     
     */
    public void setCLASSIFICATIONCODETYPE(CodeTypeVal value) {
        this.classificationcodetype = value;
    }

    /**
     * Gets the value of the classificationcodeid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCLASSIFICATIONCODEID() {
        return classificationcodeid;
    }

    /**
     * Sets the value of the classificationcodeid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCLASSIFICATIONCODEID(String value) {
        this.classificationcodeid = value;
    }

}
