//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.31 at 12:02:07 AM EDT 
//


package com.thomsonreuters.extractvalidator.wsdl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CodeTypeVal.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CodeTypeVal">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="INDUSTRY PRODUCT CODE"/>
 *     &lt;enumeration value="INDUSTRY CODE"/>
 *     &lt;enumeration value="CNAE CODE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CodeTypeVal")
@XmlEnum
public enum CodeTypeVal {

    @XmlEnumValue("INDUSTRY PRODUCT CODE")
    INDUSTRY_PRODUCT_CODE("INDUSTRY PRODUCT CODE"),
    @XmlEnumValue("INDUSTRY CODE")
    INDUSTRY_CODE("INDUSTRY CODE"),
    @XmlEnumValue("CNAE CODE")
    CNAE_CODE("CNAE CODE");
    private final String value;

    CodeTypeVal(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CodeTypeVal fromValue(String v) {
        for (CodeTypeVal c: CodeTypeVal.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
