//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.31 at 12:02:07 AM EDT 
//


package com.thomsonreuters.extractvalidator.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				
 * List of established locations.
 * 		
 * 			
 * 
 * <p>Java class for EstablishmentsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EstablishmentsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="BUYER_ROLE" type="{http://www.sabrix.com/services/taxcalculationservice/2011-09-01}EstablishmentsLocationType" minOccurs="0"/>
 *         &lt;element name="MIDDLEMAN_ROLE" type="{http://www.sabrix.com/services/taxcalculationservice/2011-09-01}EstablishmentsLocationType" minOccurs="0"/>
 *         &lt;element name="SELLER_ROLE" type="{http://www.sabrix.com/services/taxcalculationservice/2011-09-01}EstablishmentsLocationType" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EstablishmentsType", propOrder = {

})
public class EstablishmentsType {

    @XmlElement(name = "BUYER_ROLE")
    protected EstablishmentsLocationType buyerrole;
    @XmlElement(name = "MIDDLEMAN_ROLE")
    protected EstablishmentsLocationType middlemanrole;
    @XmlElement(name = "SELLER_ROLE")
    protected EstablishmentsLocationType sellerrole;

    /**
     * Gets the value of the buyerrole property.
     * 
     * @return
     *     possible object is
     *     {@link EstablishmentsLocationType }
     *     
     */
    public EstablishmentsLocationType getBUYERROLE() {
        return buyerrole;
    }

    /**
     * Sets the value of the buyerrole property.
     * 
     * @param value
     *     allowed object is
     *     {@link EstablishmentsLocationType }
     *     
     */
    public void setBUYERROLE(EstablishmentsLocationType value) {
        this.buyerrole = value;
    }

    /**
     * Gets the value of the middlemanrole property.
     * 
     * @return
     *     possible object is
     *     {@link EstablishmentsLocationType }
     *     
     */
    public EstablishmentsLocationType getMIDDLEMANROLE() {
        return middlemanrole;
    }

    /**
     * Sets the value of the middlemanrole property.
     * 
     * @param value
     *     allowed object is
     *     {@link EstablishmentsLocationType }
     *     
     */
    public void setMIDDLEMANROLE(EstablishmentsLocationType value) {
        this.middlemanrole = value;
    }

    /**
     * Gets the value of the sellerrole property.
     * 
     * @return
     *     possible object is
     *     {@link EstablishmentsLocationType }
     *     
     */
    public EstablishmentsLocationType getSELLERROLE() {
        return sellerrole;
    }

    /**
     * Sets the value of the sellerrole property.
     * 
     * @param value
     *     allowed object is
     *     {@link EstablishmentsLocationType }
     *     
     */
    public void setSELLERROLE(EstablishmentsLocationType value) {
        this.sellerrole = value;
    }

}
