//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.31 at 12:02:07 AM EDT 
//


package com.thomsonreuters.extractvalidator.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				
 * Contains pass-through elements used to identify the originating request from the ERP source.
 * 		
 * 			
 * 
 * <p>Java class for HostRequestInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HostRequestInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="HOST_REQUEST_ID" type="{http://www.sabrix.com/services/taxcalculationservice/2011-09-01}HostRequestIdType" minOccurs="0"/>
 *         &lt;element name="HOST_REQUEST_LOG_ENTRY_ID" type="{http://www.sabrix.com/services/taxcalculationservice/2011-09-01}HostRequestLogEntryIdType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HostRequestInfoType", propOrder = {
    "hostrequestid",
    "hostrequestlogentryid"
})
public class HostRequestInfoType {

    @XmlElement(name = "HOST_REQUEST_ID")
    protected String hostrequestid;
    @XmlElement(name = "HOST_REQUEST_LOG_ENTRY_ID")
    protected String hostrequestlogentryid;

    /**
     * Gets the value of the hostrequestid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHOSTREQUESTID() {
        return hostrequestid;
    }

    /**
     * Sets the value of the hostrequestid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHOSTREQUESTID(String value) {
        this.hostrequestid = value;
    }

    /**
     * Gets the value of the hostrequestlogentryid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHOSTREQUESTLOGENTRYID() {
        return hostrequestlogentryid;
    }

    /**
     * Sets the value of the hostrequestlogentryid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHOSTREQUESTLOGENTRYID(String value) {
        this.hostrequestlogentryid = value;
    }

}
