//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.31 at 12:02:07 AM EDT 
//


package com.thomsonreuters.extractvalidator.wsdl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.thomsonreuters.extractvalidator.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TaxCalculationResponse_QNAME = new QName("http://www.sabrix.com/services/taxcalculationservice/2011-09-01", "taxCalculationResponse");
    private final static QName _TaxCalculationFault_QNAME = new QName("http://www.sabrix.com/services/taxcalculationservice/2011-09-01", "taxCalculationFault");
    private final static QName _TaxCalculationRequest_QNAME = new QName("http://www.sabrix.com/services/taxcalculationservice/2011-09-01", "taxCalculationRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.thomsonreuters.extractvalidator.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OperatingLicensesType }
     * 
     */
    public OperatingLicensesType createOperatingLicensesType() {
        return new OperatingLicensesType();
    }

    /**
     * Create an instance of {@link CodesType }
     * 
     */
    public CodesType createCodesType() {
        return new CodesType();
    }

    /**
     * Create an instance of {@link OutdataLicensesType }
     * 
     */
    public OutdataLicensesType createOutdataLicensesType() {
        return new OutdataLicensesType();
    }

    /**
     * Create an instance of {@link IndataLicensesDetailType }
     * 
     */
    public IndataLicensesDetailType createIndataLicensesDetailType() {
        return new IndataLicensesDetailType();
    }

    /**
     * Create an instance of {@link OutdataLicenseType }
     * 
     */
    public OutdataLicenseType createOutdataLicenseType() {
        return new OutdataLicenseType();
    }

    /**
     * Create an instance of {@link FlagAddressType }
     * 
     */
    public FlagAddressType createFlagAddressType() {
        return new FlagAddressType();
    }

    /**
     * Create an instance of {@link ThresholdResultType }
     * 
     */
    public ThresholdResultType createThresholdResultType() {
        return new ThresholdResultType();
    }

    /**
     * Create an instance of {@link TaxCalculationResponse }
     * 
     */
    public TaxCalculationResponse createTaxCalculationResponse() {
        return new TaxCalculationResponse();
    }

    /**
     * Create an instance of {@link QuantitiesType }
     * 
     */
    public QuantitiesType createQuantitiesType() {
        return new QuantitiesType();
    }

    /**
     * Create an instance of {@link CurrencyConversionType }
     * 
     */
    public CurrencyConversionType createCurrencyConversionType() {
        return new CurrencyConversionType();
    }

    /**
     * Create an instance of {@link CommonAddressType }
     * 
     */
    public CommonAddressType createCommonAddressType() {
        return new CommonAddressType();
    }

    /**
     * Create an instance of {@link LocationNameType }
     * 
     */
    public LocationNameType createLocationNameType() {
        return new LocationNameType();
    }

    /**
     * Create an instance of {@link IndataLicensesType }
     * 
     */
    public IndataLicensesType createIndataLicensesType() {
        return new IndataLicensesType();
    }

    /**
     * Create an instance of {@link RegistrationsType }
     * 
     */
    public RegistrationsType createRegistrationsType() {
        return new RegistrationsType();
    }

    /**
     * Create an instance of {@link PricesType }
     * 
     */
    public PricesType createPricesType() {
        return new PricesType();
    }

    /**
     * Create an instance of {@link CertificateLocationType }
     * 
     */
    public CertificateLocationType createCertificateLocationType() {
        return new CertificateLocationType();
    }

    /**
     * Create an instance of {@link OutdataRequestStatusType }
     * 
     */
    public OutdataRequestStatusType createOutdataRequestStatusType() {
        return new OutdataRequestStatusType();
    }

    /**
     * Create an instance of {@link FeeType }
     * 
     */
    public FeeType createFeeType() {
        return new FeeType();
    }

    /**
     * Create an instance of {@link ZoneAddressType }
     * 
     */
    public ZoneAddressType createZoneAddressType() {
        return new ZoneAddressType();
    }

    /**
     * Create an instance of {@link OutdataLineType }
     * 
     */
    public OutdataLineType createOutdataLineType() {
        return new OutdataLineType();
    }

    /**
     * Create an instance of {@link InclusiveTaxIndicatorsType }
     * 
     */
    public InclusiveTaxIndicatorsType createInclusiveTaxIndicatorsType() {
        return new InclusiveTaxIndicatorsType();
    }

    /**
     * Create an instance of {@link TaxCalculationRequest }
     * 
     */
    public TaxCalculationRequest createTaxCalculationRequest() {
        return new TaxCalculationRequest();
    }

    /**
     * Create an instance of {@link IndataType }
     * 
     */
    public IndataType createIndataType() {
        return new IndataType();
    }

    /**
     * Create an instance of {@link PriceType }
     * 
     */
    public PriceType createPriceType() {
        return new PriceType();
    }

    /**
     * Create an instance of {@link UomConversionType }
     * 
     */
    public UomConversionType createUomConversionType() {
        return new UomConversionType();
    }

    /**
     * Create an instance of {@link IndataLineType }
     * 
     */
    public IndataLineType createIndataLineType() {
        return new IndataLineType();
    }

    /**
     * Create an instance of {@link ConvertedCurrencyAmountType }
     * 
     */
    public ConvertedCurrencyAmountType createConvertedCurrencyAmountType() {
        return new ConvertedCurrencyAmountType();
    }

    /**
     * Create an instance of {@link BuyerOrSellerLicenseType }
     * 
     */
    public BuyerOrSellerLicenseType createBuyerOrSellerLicenseType() {
        return new BuyerOrSellerLicenseType();
    }

    /**
     * Create an instance of {@link AuthorityAttributeType }
     * 
     */
    public AuthorityAttributeType createAuthorityAttributeType() {
        return new AuthorityAttributeType();
    }

    /**
     * Create an instance of {@link UserElementAmountType }
     * 
     */
    public UserElementAmountType createUserElementAmountType() {
        return new UserElementAmountType();
    }

    /**
     * Create an instance of {@link OutdataType }
     * 
     */
    public OutdataType createOutdataType() {
        return new OutdataType();
    }

    /**
     * Create an instance of {@link OutdataTaxSummaryType }
     * 
     */
    public OutdataTaxSummaryType createOutdataTaxSummaryType() {
        return new OutdataTaxSummaryType();
    }

    /**
     * Create an instance of {@link AmountType }
     * 
     */
    public AmountType createAmountType() {
        return new AmountType();
    }

    /**
     * Create an instance of {@link IndataInvoiceType }
     * 
     */
    public IndataInvoiceType createIndataInvoiceType() {
        return new IndataInvoiceType();
    }

    /**
     * Create an instance of {@link OutdataAdvisoriesType }
     * 
     */
    public OutdataAdvisoriesType createOutdataAdvisoriesType() {
        return new OutdataAdvisoriesType();
    }

    /**
     * Create an instance of {@link CurrencyConversionStepType }
     * 
     */
    public CurrencyConversionStepType createCurrencyConversionStepType() {
        return new CurrencyConversionStepType();
    }

    /**
     * Create an instance of {@link BillOfLadingType }
     * 
     */
    public BillOfLadingType createBillOfLadingType() {
        return new BillOfLadingType();
    }

    /**
     * Create an instance of {@link CodeType }
     * 
     */
    public CodeType createCodeType() {
        return new CodeType();
    }

    /**
     * Create an instance of {@link QuantityType }
     * 
     */
    public QuantityType createQuantityType() {
        return new QuantityType();
    }

    /**
     * Create an instance of {@link TaxCalculationFault }
     * 
     */
    public TaxCalculationFault createTaxCalculationFault() {
        return new TaxCalculationFault();
    }

    /**
     * Create an instance of {@link UserElementDateType }
     * 
     */
    public UserElementDateType createUserElementDateType() {
        return new UserElementDateType();
    }

    /**
     * Create an instance of {@link OutdataInvoiceType }
     * 
     */
    public OutdataInvoiceType createOutdataInvoiceType() {
        return new OutdataInvoiceType();
    }

    /**
     * Create an instance of {@link UserElementType }
     * 
     */
    public UserElementType createUserElementType() {
        return new UserElementType();
    }

    /**
     * Create an instance of {@link OutdataTaxType }
     * 
     */
    public OutdataTaxType createOutdataTaxType() {
        return new OutdataTaxType();
    }

    /**
     * Create an instance of {@link HostRequestInfoType }
     * 
     */
    public HostRequestInfoType createHostRequestInfoType() {
        return new HostRequestInfoType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link OutdataErrorType }
     * 
     */
    public OutdataErrorType createOutdataErrorType() {
        return new OutdataErrorType();
    }

    /**
     * Create an instance of {@link EstablishmentsLocationType }
     * 
     */
    public EstablishmentsLocationType createEstablishmentsLocationType() {
        return new EstablishmentsLocationType();
    }

    /**
     * Create an instance of {@link MessageType }
     * 
     */
    public MessageType createMessageType() {
        return new MessageType();
    }

    /**
     * Create an instance of {@link EstablishmentsType }
     * 
     */
    public EstablishmentsType createEstablishmentsType() {
        return new EstablishmentsType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TaxCalculationResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sabrix.com/services/taxcalculationservice/2011-09-01", name = "taxCalculationResponse")
    public JAXBElement<TaxCalculationResponse> createTaxCalculationResponse(TaxCalculationResponse value) {
        return new JAXBElement<TaxCalculationResponse>(_TaxCalculationResponse_QNAME, TaxCalculationResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TaxCalculationFault }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sabrix.com/services/taxcalculationservice/2011-09-01", name = "taxCalculationFault")
    public JAXBElement<TaxCalculationFault> createTaxCalculationFault(TaxCalculationFault value) {
        return new JAXBElement<TaxCalculationFault>(_TaxCalculationFault_QNAME, TaxCalculationFault.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TaxCalculationRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sabrix.com/services/taxcalculationservice/2011-09-01", name = "taxCalculationRequest")
    public JAXBElement<TaxCalculationRequest> createTaxCalculationRequest(TaxCalculationRequest value) {
        return new JAXBElement<TaxCalculationRequest>(_TaxCalculationRequest_QNAME, TaxCalculationRequest.class, null, value);
    }

}
