//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.31 at 12:02:07 AM EDT 
//


package com.thomsonreuters.extractvalidator.wsdl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Optional, max occurs 1 per document/invoice, wrapper for operating license types.
 * 			
 * 
 * <p>Java class for OperatingLicensesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OperatingLicensesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ASSUME_BUYER_FULLY_LICENSED" type="{http://www.sabrix.com/services/taxcalculationservice/2011-09-01}BooleanType" minOccurs="0"/>
 *         &lt;element name="BUYER" type="{http://www.sabrix.com/services/taxcalculationservice/2011-09-01}BuyerOrSellerLicenseType" maxOccurs="10" minOccurs="0"/>
 *         &lt;element name="ASSUME_SELLER_FULLY_LICENSED" type="{http://www.sabrix.com/services/taxcalculationservice/2011-09-01}BooleanType" minOccurs="0"/>
 *         &lt;element name="SELLER" type="{http://www.sabrix.com/services/taxcalculationservice/2011-09-01}BuyerOrSellerLicenseType" maxOccurs="10" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OperatingLicensesType", propOrder = {
    "assumebuyerfullylicensed",
    "buyer",
    "assumesellerfullylicensed",
    "seller"
})
public class OperatingLicensesType {

    @XmlElement(name = "ASSUME_BUYER_FULLY_LICENSED")
    protected String assumebuyerfullylicensed;
    @XmlElement(name = "BUYER")
    protected List<BuyerOrSellerLicenseType> buyer;
    @XmlElement(name = "ASSUME_SELLER_FULLY_LICENSED")
    protected String assumesellerfullylicensed;
    @XmlElement(name = "SELLER")
    protected List<BuyerOrSellerLicenseType> seller;

    /**
     * Gets the value of the assumebuyerfullylicensed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getASSUMEBUYERFULLYLICENSED() {
        return assumebuyerfullylicensed;
    }

    /**
     * Sets the value of the assumebuyerfullylicensed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setASSUMEBUYERFULLYLICENSED(String value) {
        this.assumebuyerfullylicensed = value;
    }

    /**
     * Gets the value of the buyer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the buyer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBUYER().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BuyerOrSellerLicenseType }
     * 
     * 
     */
    public List<BuyerOrSellerLicenseType> getBUYER() {
        if (buyer == null) {
            buyer = new ArrayList<BuyerOrSellerLicenseType>();
        }
        return this.buyer;
    }

    /**
     * Gets the value of the assumesellerfullylicensed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getASSUMESELLERFULLYLICENSED() {
        return assumesellerfullylicensed;
    }

    /**
     * Sets the value of the assumesellerfullylicensed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setASSUMESELLERFULLYLICENSED(String value) {
        this.assumesellerfullylicensed = value;
    }

    /**
     * Gets the value of the seller property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the seller property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSELLER().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BuyerOrSellerLicenseType }
     * 
     * 
     */
    public List<BuyerOrSellerLicenseType> getSELLER() {
        if (seller == null) {
            seller = new ArrayList<BuyerOrSellerLicenseType>();
        }
        return this.seller;
    }

}
