//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.31 at 12:02:07 AM EDT 
//


package com.thomsonreuters.extractvalidator.wsdl;

import javax.xml.bind.annotation.*;


/**
 * 
 * 				
 * The top level response to a request for tax calculation.
 * 				
 * 			
 * 
 * <p>Java class for TaxCalculationResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TaxCalculationResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OUTDATA" type="{http://www.sabrix.com/services/taxcalculationservice/2011-09-01}OutdataType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TaxCalculationResponse", propOrder = {
    "outdata"
})
@XmlRootElement(name = "taxCalculationResponse")
public class TaxCalculationResponse {

    @XmlElement(name = "OUTDATA", required = true)
    protected OutdataType outdata;

    /**
     * Gets the value of the outdata property.
     * 
     * @return
     *     possible object is
     *     {@link OutdataType }
     *     
     */
    public OutdataType getOUTDATA() {
        return outdata;
    }

    /**
     * Sets the value of the outdata property.
     * 
     * @param value
     *     allowed object is
     *     {@link OutdataType }
     *     
     */
    public void setOUTDATA(OutdataType value) {
        this.outdata = value;
    }

}
